#./hosts/zephyrus-m16/default.nix
{ inputs,... }:

{
  imports = [
    # Hardware-specific configuration generated by the installer
   ./hardware-configuration.nix

    # Core system modules
   ../../modules/system/base.nix
   ../../modules/system/gnome.nix

    # Hardware-specific tweaks and fixes for this model
   ../../modules/system/hardware/asus-zephyrus-m16.nix

    # Home Manager configuration for your user
    inputs.home-manager.nixosModules.home-manager
    {
      home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;
        users.hbohlen = import../../modules/home-manager/hbohlen.nix;
      };
    }
  ];

  # Set the system state version
  system.stateVersion = "25.05";
}
